_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Horizon Europe NI'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 934008c1-620f-454a-b0ac-4ec66b1db671
frontpage_title: 'Welcome to Drupal site'
