_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 7b524741-f6b5-4550-86a9-535a9b0aa66b
name: 'Independent Panel Truth Recovery NI'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/17
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Independent Panel Truth Recovery NI'
frontpage_show_title: 0
