_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 94dcc4e5-a86f-4ddc-aad2-cd8d576a2549
name: 'Parole Commissioners for Northern Ireland'
mail: Referrals@parolecomni.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
