_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 27651f46-26e4-46ed-80e2-d556485f62f2
name: 'Local Government Boundaries Commissioner for Northern Ireland'
mail: info@lgbc-ni.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
