#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://www.pacni.gov.uk.{default}/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://pacni.gov.uk.{default}/':
    type: redirect
    to: 'https://www.pacni.gov.uk.{default}/'
'https://www.judiciaryni.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://judiciaryni.uk/':
    type: redirect
    to: 'https://www.judiciaryni.uk/'
'https://www.boundarycommission.org.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://boundarycommission.org.uk/':
    type: redirect
    to: 'https://www.boundarycommission.org.uk/'
'https://www.industrialcourt.gov.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://industrialcourt.gov.uk/':
    type: redirect
    to: 'https://www.industrialcourt.gov.uk/'
'https://www.interchangeni.org.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://interchangeni.org.uk/':
    type: redirect
    to: 'https://www.interchangeni.org.uk/'
'https://www.info.library.nics.gov.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://info.library.nics.gov.uk/':
    type: redirect
    to: 'https://www.info.library.nics.gov.uk/'
'https://www.pressclippings.nics.gov.uk/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://pressclippings.nics.gov.uk/':
    type: redirect
    to: 'https://www.pressclippings.nics.gov.uk/'
'https://www.{all}/':
    type: upstream
    upstream: 'unity_svr_3:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
